urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.urls import path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    url(r'^$', home, name='home'),
    path('books', book_list, name='books'),
    path('book/form', book_form, name='book_form'),
    path('book/<int:book_id>/', book_details, name="book"),
    path('librarians', list_librarians, name='librarians'),
    path('librarian/<int:librarian_id>/', librarian_details, name='librarian'),
    path('libraries', library_list, name='libraries'),
    path('library/<int:library_id>/', library_details, name='library'),
    path('library/form', library_form, name='library_form'),
    path('logout/', logout_user, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]

models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian

class Book(models.Model):

    title = models.CharField(max_length=100)
    ISBN = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    year_published = models.IntegerField()
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

models/library.py
from django.db import models

class Library(models.Model):

    title = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    

models/modelfactory.py
import sqlite3

def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

views/connection.py
class Connection:
    db_path = "/Users/DannyBarker/workspace/python/libraryproject/db.sqlite3"

views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

templates/books/detail.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>{{ book.title }}</h1>
<h2>By {{ book.author }}</h2>

<div>Published in {{ book.year_published }}</div>
<div>ISBN: {{ book.ISBN }}</div>
<div>Location: <a href={% url 'libraryapp:library' book.library_id %}>{{ book.library_name }}</a></div>
<div>Registered by Admin <a href={% url 'libraryapp:librarian' book.user_id%}>{{ book.first_name }} {{ book.last_name }}</a></div>
<form action="{% url 'libraryapp:book' book.id %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="actual_method" value="DELETE">
  <button>Delete</button>
</form>
<form action="{% url 'libraryapp:book' book.id %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="actual_method" value="EDIT">
  <button>Edit</button>
</form>
{% endblock %}

templates/books/form.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>Inventory Book</h1>

<form action="{% url 'libraryapp:books' %}" method="post">
  {% csrf_token %}
  {% if book.id is not None %}
  <input type="hidden" name="book_id" value="{{ book.id }}" />
  {% endif %}
  <fieldset>
      <label for="title">Title: </label>
      <input id="title" type="text" name="title" value="{{ book.title }}">
  </fieldset>
  <fieldset>
      <label for="author">Author: </label>
      <input id="author" type="text" name="author" value="{{ book.author }}">
  </fieldset>
  <fieldset>
      <label for="year_published">Year of publication: </label>
      <input id="year_published" type="number" name="year_published" value="{{ book.year_published }}">
  </fieldset>
  <fieldset>
      <label for="isbn">ISBN: </label>
      <input id="isbn" type="text" name="isbn" value="{{ book.ISBN }}">
  </fieldset>
  <fieldset>
      <label for="location">Library: </label>
      <select id="location" type="text" name="location">
            {% for library in libraries %}
                <option value="{{ library.id }}" {% if library.id == book.location_id %}selected{% endif %}>{{ library.title }}</option>
            {% endfor %}
      </select>
  </fieldset>

  {% if book.id is not None %}
  <input type="submit" name="actual_method" value="Add It" />
  {% else %}
  <input type="submit" value="Add It" />
  {% endif %}
</form>
{% endblock %}

templates/books/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'styles/books.css' %}" />
{% endblock %}

{% block content %}
    <h1>Books</h1>

    <dialog class="infoDialog">
        <div class="infoDialog__message"></div>
        <button class="closeDialog">Close</button>
    </dialog>

    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    <ol class="books">
    {% for book in all_books %}
        <li class="book">
            <a class="book__title" href="{% url 'libraryapp:book' book.id %}"> {{ book.title }}</a>
            <div class="book__description">
                by {{book.author}} published in {{book.year_published}}
            </div>
            <button id="detail--{{ book.id }}">Details</button>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/books.js' %}"></script>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

templates/librarians/detail.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>{{ librarian.librarian_first }} {{ librarian.librarian_last }}</h1>

<div>Location: <a href={% url 'libraryapp:library' librarian.location_id %}>{{ librarian.location_name }}</a></div>
{% endblock %}

templates/librarians/list.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>Librarians</h1>

<ol>
{% for librarian in all_librarians %}
    <li><a href={% url 'libraryapp:librarian' librarian.id %}>{{ librarian.first_name }} {{ librarian.last_name }}</a></li>
{% endfor %}
</ol>
{% endblock %}

templates/libraries/detail.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>{{ library.title }}</h1>

<div>Address: <address>{{ library.address }}</address></div>
<form action="{% url 'libraryapp:library' library.id %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="actual_method" value="DELETE">
  <button>Delete</button>
</form>
{% endblock %}

templates/libraries/form.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>Add Library</h1>


<form action="{% url 'libraryapp:libraries' %}" method="post">
  {% csrf_token %}
  <fieldset>
      <label for="title">Name: </label>
      <input id="title" type="text" name="title">
  </fieldset>
  <fieldset>
      <label for="author">Address: </label>
      <textarea id="address" type="text" name="address"></textarea>
  </fieldset>

  <input type="submit" value="Add It" />
</form>
{% endblock %}

templates/libraries/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Libraries</h1>

    <a href="{% url 'libraryapp:library_form' %}">Add Library</a>

    <ol>
    {% for library in all_libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}">
                {{ library.title }}
            </a>
            ({{ library.address }})
            {% if library.books|length > 0 %}
            <ul>
            {% for book in library.books %}
                <a href={% url 'libraryapp:book' book.id %}><li>{{ book.title }}</a></li>
            {% endfor %}
            </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ol>
{% endblock %}

templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:logout' %}">Logout</a></li>
        </ol>
    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>